#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SocialIntegration.Resource", IsApplication=true)]

namespace SocialIntegration
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_buttons = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int backrepeat = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_facebook_retina = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_facebook_retina_pressed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_twitter_retina = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_twitter_retina_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int facebook_button = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int monoandroidsplash = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int pattern = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int running_girl = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int selection_buttons = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int splash_button = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int twitter_button = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int Advanced = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int Beginner = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int CreateWorkout = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int Equip = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int GetLean = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int GetToned = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int ImpromptuWorkout = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int Intermediate = 2131099651;
			
			// aapt resource value: 0x7f06000d
			public const int LoginButton = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int LoginFacebookButton = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int LoginTwitterButton = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int ShareFacebookButton = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int ShareTwitterButton = 2131099665;
			
			// aapt resource value: 0x7f060000
			public const int Stats = 2131099648;
			
			// aapt resource value: 0x7f060012
			public const int button1 = 2131099666;
			
			// aapt resource value: 0x7f060005
			public const int t15min = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int t30min = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int t45min = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int wEquip = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dashboard = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DifficultySelection = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DurationSelection = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EquipmentSelection = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int GoalSelection = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int InitialScreen = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int WorkoutScreen = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int CreateWorkout = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int LoginButton = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int LoginFacebookButton = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int LoginTwitterButton = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ShareFacebookButton = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ShareTwitterButton = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int Stats = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Mono_Android_Theme_Splash = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int button_text = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
